name: Setup Backend
description: Setup Python and install dependencies

runs:
  using: composite
  steps:
    - name: Extract Python version from Pipfile
      id: extract-python-version
      run: |
        PYTHON_VERSION=$(grep -Po '(?<=python_version\s=\s")[^"]+' Pipfile)
        echo "Detected Python version: $PYTHON_VERSION"
        echo "python-version=$PYTHON_VERSION" >> $GITHUB_OUTPUT
      shell: bash
      working-directory: starter/backend

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ steps.extract-python-version.outputs.python-version }}

    - name: Install pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
      shell: bash
      working-directory: starter/backend

    - name: Cache dependencies
      id: pipenv-cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pip
          ~/.local/share/virtualenvs
        key: ${{ runner.os }}-pipenv-${{ hashFiles('starter/backend/Pipfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pipenv-

    - name: Install dev dependencies
      run: pipenv install --dev
      shell: bash
      working-directory: starter/backend

    - name: Install dependencies
      if: steps.pipenv-cache.outputs.cache-hit != 'true'
      run: pipenv install
      shell: bash
      working-directory: starter/backend
