name: "Backend CI"

on:
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch:

  # Automatic trigger on push events to the main branch
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - "starter/backend/**"

  # Automatic trigger on pull request events targeting the main branch
  # pull_request:
  #   branches:
  #     - main
  #   paths:
  #     - "starter/backend/**"

jobs:
  lint:
    runs-on: "ubuntu-latest"

    defaults:
      run:
        working-directory: ./starter/backend
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup-backend

      - name: Lint
        run: pipenv run lint

  test:
    runs-on: "ubuntu-latest"

    defaults:
      run:
        working-directory: ./starter/backend
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup-backend

      - name: Check if flake8 is installed
        run: pipenv run flake8 --version
        shell: bash
        working-directory: starter/backend

      - name: Test
        run: pipenv run test

  build:
    needs: [lint, test]

    runs-on: "ubuntu-latest"

    defaults:
      run:
        working-directory: ./starter/backend
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup-backend
