name: "Frontend Continuous Integration"

on:
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch:

  # Automatic trigger on pull request events targeting the main branch
  pull_request:
    branches:
      - main
    paths:
      - "starter/frontend/**"

env:
  REACT_APP_MOVIE_API_URL: "http://localhost:5000"

jobs:
  lint:
    runs-on: "ubuntu-latest"

    defaults:
      run:
        working-directory: ./starter/frontend
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup-frontend

      - name: Lint
        run: npm run lint

  test:
    runs-on: "ubuntu-latest"

    defaults:
      run:
        working-directory: ./starter/frontend
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup-frontend

      - name: Test
        run: CI=true npm test

  build:
    needs: [lint, test]

    runs-on: "ubuntu-latest"

    defaults:
      run:
        working-directory: ./starter/frontend
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: docker build --build-arg=REACT_APP_MOVIE_API_URL=${{ env.REACT_APP_MOVIE_API_URL }} --tag=mp-frontend:${{ github.sha }} .
