name: "Frontend CI"

on:
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch:

  # Automatic trigger on push events to the main branch
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - "starter/frontend/**"

  # Automatic trigger on pull request events targeting the main branch
  # pull_request:
  #   branches:
  #     - main
  #   paths:
  #     - "starter/frontend/**"

jobs:
  lint:
    runs-on: "ubuntu-latest"

    defaults:
      run:
        working-directory: ./starter/frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup-frontend

      - name: Lint
        run: npm run lint

  test:
    runs-on: "ubuntu-latest"

    defaults:
      run:
        working-directory: ./starter/frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup-frontend

      - name: Test
        run: CI=true npm test

  build:
    needs: [lint, test]

    runs-on: "ubuntu-latest"

    defaults:
      run:
        working-directory: ./starter/frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup-frontend
